---
  title: ""
  permalink: /cv/
---

# Skills and Knowledge

My main tool for anything data related is **R**. My typical workflow uses the [**tidyverse**](https://www.tidyverse.org/) and [**data.table**](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) package.  

<!-- Use formattable package to create  -->
<div class="row">
<div class="column">
<h3>Domain Knowledge</h3><p>
- Infectious Disease Epidemiology  
- Disease Surveillance  
- Statistical Programming  
- Environmental Analytics  
- Vector-borne Diseases
</p>
</div>
<div class="column">
<h3>Soft Skills</h3><p>
- Problem Solving  
- Critical Thinking  
- Effective Communication    
- Interpersonal Skills  
</p>
</div>
<div class="column">
<h3>Technical Skills</h3><p>
- Descriptive Data Analysis  
- Data Processing  
- Data Visualization  
- Programming  
- Regular Expression  
- Spatial Data Analysis  
- RDBMS Query and Design  
- Machine Learning  
</p>
</div>
<div class="column">
<h3>Tools</h3><p>
- R  
- SQL, PostgreSQL  
- Git, GitHub  
- Python  
- ArcGIS, QGIS  
- HTML, CSS  
- Matlab  
- SAS   
</p>
</div>
</div>

<br>

# Experiences

<div class="row">
<div class="column">
<h3>Other Skills and Experiences</h3><p>
- Scientific Writing  
- Knowledge Translation  
- OS (Windows, Mac)  
- Reference Management (Refworks, Zotero)  
- Image Editing and Processing  (Adobe Photoshop, Illustrator)  
- Microsoft Office Suite (Word, Excel, Powerpoint, Outlook)  
- Project Management  
- Hiring Management and Interviews  
</p>
</div>
</div>

More of my experiences can be found in my [**LinkedIn profile**](www.linkedin.com/in/eugejoh) at the top right of the navigation bar.  

<!-- <div class="column-left"> -->
<!-- **Domain Knowledge:**   -->
<!-- - Infectious Disease Epidemiology   -->
<!-- - Disease Surveillance   -->
<!-- - One Health   -->
<!-- - Environmental Analytics   -->
<!-- - Statistical Programming   -->
<!-- </div> -->

<!-- <div class="column-center"> -->
<!-- **Technical Skills:**   -->
<!-- - Exploratory Data Analysis (5)   -->
<!-- - Data Processing (5)   -->
<!-- - Data Visualization (5)   -->
<!-- - Programming (4)   -->
<!-- - Spatial Data Processing and Analysis (3)   -->
<!-- - RDBMS Query and Design (3)   -->
<!-- - Machine Learning (2)   -->
<!-- </div> -->

<!-- <div class="column-right"> -->
<!-- **Soft Skills:**   -->
<!-- - Problem Solving   -->
<!-- - Critical Thinking   -->
<!-- - Collaboration   -->
<!-- - Interpersonal Skills   -->
<!-- - Active Learning   -->
<!-- </div> -->

<!-- <br> -->

<!-- <div class="column-left"> -->
<!-- **Tools:**   -->
<!-- - R (5)   -->
<!-- - Python (3)   -->
<!-- - SQL, PostgreSQL (3)   -->
<!-- - Git, GitHub (3)   -->
<!-- - ArcGIS, QGIS (3)   -->
<!-- - HTML, CSS (2) -->
<!-- - Matlab (2)   -->
<!-- - SAS (1)   -->
<!-- </div> -->

<!-- <div class="column-center"> -->
<!-- **Other Skills and Experiences:**   -->
<!-- - Scientific Writing   -->
<!-- - Knowledge Translation   -->
<!-- - OS (Windows, Mac)   -->
<!-- - Reference Management (Refworks, Zotero)   -->
<!-- - Image Editing and Processing  (Adobe Photoshop, Illustrator)   -->
<!-- - Microsoft Office Suite (Word, Excel, Powerpoint, Outlook)   -->
<!-- - Hiring Management and Interviews   -->
<!-- </div> -->

<!-- <br> -->

